name: Building Program
run-name: Building ${{ GITHUB.REPOSITORY }}

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  call-meimei:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-meimei.yml@master
    secrets: inherit

  call-arm64-zhuangzhuang:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base.yml@master
    secrets: inherit
    with:
      display-name: arm64-zhuangzhuang
      arch: arm64
      rootfs-codename: trixie
      rootfs-source: https://deb.debian.org/debian/
      gxde-codename: lizhi
      gxde-codename-upload: zhuangzhuang

  call-arm64-tianlu:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base.yml@master
    secrets: inherit
    with:
      display-name: arm64-tianlu
      arch: arm64
      rootfs-codename: bookworm
      rootfs-source: https://deb.debian.org/debian/
      gxde-codename: bixie
      gxde-codename-upload: tianlu

  call-loong64-tianlu:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base.yml@master
    secrets: inherit
    with:
      display-name: loong64-tianlu
      arch: loong64
      rootfs-codename: sid
      rootfs-source: https://deb.debian.org/debian-ports/
      gxde-codename: bixie
      gxde-codename-upload: tianlu
